package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/rohanthewiz/logger"
	"github.com/rohanthewiz/rweb"
	"github.com/rohanthewiz/serr"
)

// envFilePath is the relative path to the .env file that the spoke reads on
// startup. Using a constant keeps this in sync with main.go's
// fileops.EnvFromFile("config/cfg_files/.env") call.
const envFilePath = "config/cfg_files/.env"

// ApplySpokeConfig handles POST /api/v1/setup/apply
// Writes sync configuration from an exported JSON file to the .env file.
// This endpoint does NOT require authentication because it is used during
// initial spoke setup before any users exist on the spoke.
//
// Guard: only available when sync is not yet configured. Once
// GONOTES_SYNC_ENABLED is "true", this endpoint returns 403 to prevent
// accidental reconfiguration of a running spoke.
//
// Request body: SpokeExportConfig JSON (same struct used by the export).
func ApplySpokeConfig(ctx rweb.Context) error {
	// First-run guard — if sync is already enabled, refuse to overwrite.
	// This prevents a rogue request from reconfiguring a live spoke.
	if strings.EqualFold(os.Getenv("GONOTES_SYNC_ENABLED"), "true") {
		return writeError(ctx, http.StatusForbidden,
			"sync is already configured; edit the .env file manually to reconfigure")
	}

	// Parse the import config
	var cfg SpokeExportConfig
	if err := json.Unmarshal(ctx.Request().Body(), &cfg); err != nil {
		return writeError(ctx, http.StatusBadRequest, "invalid config JSON")
	}

	// Validate required fields — without these, sync can't function
	if cfg.HubURL == "" || cfg.Username == "" || cfg.PasswordB64 == "" {
		return writeError(ctx, http.StatusBadRequest,
			"hub_url, username, and password_b64 are required")
	}

	// Default the sync interval if not provided
	if cfg.SyncInterval == "" {
		cfg.SyncInterval = "5m"
	}

	// Default the trigger to prompt mode, matching LoadSyncConfig. A config
	// file exported by an older hub says nothing about mode, and the safe
	// reading of silence is the one where nothing leaves the machine unasked.
	if cfg.SyncMode == "" {
		cfg.SyncMode = "prompt"
	}
	if cfg.PromptAfter == "" {
		cfg.PromptAfter = "2h"
	}

	// Write the .env file with restrictive permissions (owner read/write only)
	if err := writeEnvFile(cfg); err != nil {
		logger.LogErr(serr.Wrap(err, "failed to write .env file during setup"), "path", envFilePath)
		return writeError(ctx, http.StatusInternalServerError,
			"failed to write configuration file")
	}

	logger.Info("Spoke config applied via setup", "hub_url", cfg.HubURL, "username", cfg.Username)

	return writeSuccess(ctx, http.StatusOK, map[string]string{
		"message": "Configuration saved. Restart GoNotes to activate sync.",
	})
}

// writeEnvFile writes the spoke sync configuration to config/cfg_files/.env.
// The file is written atomically (overwrite) with 0600 permissions so only
// the owner can read the credentials.
func writeEnvFile(cfg SpokeExportConfig) error {
	lines := []string{
		"# GoNotes Sync Configuration",
		"# Auto-generated by spoke setup — edit manually if needed",
		"",
		"GONOTES_SYNC_ENABLED=true",
		fmt.Sprintf("GONOTES_SYNC_HUB_URL=%s", cfg.HubURL),
		fmt.Sprintf("GONOTES_SYNC_USERNAME=%s", cfg.Username),
		fmt.Sprintf("GONOTES_SYNC_PASSWORD_B64=%s", cfg.PasswordB64),
		fmt.Sprintf("GONOTES_SYNC_INTERVAL=%s", cfg.SyncInterval),
		"",
		"# How a sync cycle is triggered: 'prompt' asks (after GONOTES_SYNC_PROMPT_AFTER,",
		"# and at exit); 'auto' runs one every GONOTES_SYNC_INTERVAL with nobody asked.",
		fmt.Sprintf("GONOTES_SYNC_MODE=%s", cfg.SyncMode),
		fmt.Sprintf("GONOTES_SYNC_PROMPT_AFTER=%s", cfg.PromptAfter),
	}

	// Invite token is optional — only include if present
	if cfg.InviteToken != "" {
		lines = append(lines, fmt.Sprintf("GONOTES_SYNC_INVITE_TOKEN=%s", cfg.InviteToken))
	}

	// JWT secret is required for the spoke to validate its own tokens
	if cfg.JWTSecret != "" {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("GONOTES_JWT_SECRET=%s", cfg.JWTSecret))
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(envFilePath, []byte(content), 0600)
}

// setEnvFileValue sets one key in config/cfg_files/.env, leaving every other
// line — including the credentials — exactly as it found them.
//
// This is deliberately not writeEnvFile: that one composes the whole file from
// a SpokeExportConfig and is right for first-run setup, where there is nothing
// to preserve. Changing one setting on a configured spoke is the opposite
// situation, and rewriting the file from a partial view of it would quietly
// drop whatever the view did not carry.
//
// The write is temp-file-plus-rename so a failure midway cannot truncate a
// file holding the hub password and the JWT secret. Permissions stay 0600.
func setEnvFileValue(key, value string) error {
	existing, err := os.ReadFile(envFilePath)
	if err != nil && !os.IsNotExist(err) {
		return serr.Wrap(err, "failed to read env file", "path", envFilePath)
	}

	line := key + "=" + value

	var out []string
	replaced := false
	for _, l := range strings.Split(string(existing), "\n") {
		// Match on the assignment, not on a Contains: a key name appearing
		// inside a comment or another value must not be rewritten.
		if strings.HasPrefix(strings.TrimSpace(l), key+"=") {
			if replaced {
				continue // a duplicate of a key we have already set: drop it
			}
			out = append(out, line)
			replaced = true
			continue
		}
		out = append(out, l)
	}

	if !replaced {
		// Append, trimming any trailing blank lines first so the file does not
		// grow a gap on every new key.
		for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
			out = out[:len(out)-1]
		}
		out = append(out, line)
	}

	content := strings.Join(out, "\n")
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}

	if err := os.MkdirAll(filepath.Dir(envFilePath), 0o700); err != nil {
		return serr.Wrap(err, "failed to create env file directory")
	}

	tmp := envFilePath + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0600); err != nil {
		return serr.Wrap(err, "failed to write temporary env file")
	}
	if err := os.Rename(tmp, envFilePath); err != nil {
		os.Remove(tmp)
		return serr.Wrap(err, "failed to replace env file")
	}
	return nil
}
