package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/rohanthewiz/logger"
	"github.com/rohanthewiz/rweb"
	"github.com/rohanthewiz/serr"
)

// envFilePath is the relative path to the .env file that the spoke reads on
// startup. Using a constant keeps this in sync with main.go's
// fileops.EnvFromFile("config/cfg_files/.env") call.
const envFilePath = "config/cfg_files/.env"

// ApplySpokeConfig handles POST /api/v1/setup/apply
// Writes sync configuration from an exported JSON file to the .env file.
// This endpoint does NOT require authentication because it is used during
// initial spoke setup before any users exist on the spoke.
//
// Guard: only available when sync is not yet configured. Once
// GONOTES_SYNC_ENABLED is "true", this endpoint returns 403 to prevent
// accidental reconfiguration of a running spoke.
//
// Request body: SpokeExportConfig JSON (same struct used by the export).
func ApplySpokeConfig(ctx rweb.Context) error {
	// First-run guard — if sync is already enabled, refuse to overwrite.
	// This prevents a rogue request from reconfiguring a live spoke.
	if strings.EqualFold(os.Getenv("GONOTES_SYNC_ENABLED"), "true") {
		return writeError(ctx, http.StatusForbidden,
			"sync is already configured; edit the .env file manually to reconfigure")
	}

	// Parse the import config
	var cfg SpokeExportConfig
	if err := json.Unmarshal(ctx.Request().Body(), &cfg); err != nil {
		return writeError(ctx, http.StatusBadRequest, "invalid config JSON")
	}

	// Validate required fields — without these, sync can't function
	if cfg.HubURL == "" || cfg.Username == "" || cfg.PasswordB64 == "" {
		return writeError(ctx, http.StatusBadRequest,
			"hub_url, username, and password_b64 are required")
	}

	// Default the sync interval if not provided
	if cfg.SyncInterval == "" {
		cfg.SyncInterval = "5m"
	}

	// Write the .env file with restrictive permissions (owner read/write only)
	if err := writeEnvFile(cfg); err != nil {
		logger.LogErr(serr.Wrap(err, "failed to write .env file during setup"), "path", envFilePath)
		return writeError(ctx, http.StatusInternalServerError,
			"failed to write configuration file")
	}

	logger.Info("Spoke config applied via setup", "hub_url", cfg.HubURL, "username", cfg.Username)

	return writeSuccess(ctx, http.StatusOK, map[string]string{
		"message": "Configuration saved. Restart GoNotes to activate sync.",
	})
}

// writeEnvFile writes the spoke sync configuration to config/cfg_files/.env.
// The file is written atomically (overwrite) with 0600 permissions so only
// the owner can read the credentials.
func writeEnvFile(cfg SpokeExportConfig) error {
	lines := []string{
		"# GoNotes Sync Configuration",
		"# Auto-generated by spoke setup — edit manually if needed",
		"",
		"GONOTES_SYNC_ENABLED=true",
		fmt.Sprintf("GONOTES_SYNC_HUB_URL=%s", cfg.HubURL),
		fmt.Sprintf("GONOTES_SYNC_USERNAME=%s", cfg.Username),
		fmt.Sprintf("GONOTES_SYNC_PASSWORD_B64=%s", cfg.PasswordB64),
		fmt.Sprintf("GONOTES_SYNC_INTERVAL=%s", cfg.SyncInterval),
	}

	// Invite token is optional — only include if present
	if cfg.InviteToken != "" {
		lines = append(lines, fmt.Sprintf("GONOTES_SYNC_INVITE_TOKEN=%s", cfg.InviteToken))
	}

	// JWT secret is required for the spoke to validate its own tokens
	if cfg.JWTSecret != "" {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("GONOTES_JWT_SECRET=%s", cfg.JWTSecret))
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(envFilePath, []byte(content), 0600)
}
